branches:
  only:
  - master
script:
  - echo "Deploying site to S3"
deploy:
  provider: s3
  access_key_id: AKIAJKG2FSL7MOLNESOA
  secret_access_key:
    secure: GNWks7xJzTYHZjZUv9DDitZNPGV5j0mOkGRbiGP92Y34pt6k857WIPpT4tAnE/gLWSzb7nPXcBUNLdSOCzZmEJFz0ICZ0RZQdJroyTRG6wM1x8F0PGWbxhJKKUbjtJtZBcDJOGqfKbRl5vWeqlfBQWjBwqGvWBwuwBTf9WB8Enw74tt4j63GZEhb1l8MDCSs4xQ6yS8o0sNmfwqye9MMj1U65tmXXCY0swqNjQ0cVwu3eqElE00y6gNf658Q8wtJV+PFdOLutx3fNqdI1JleRoO150SBkMGybCBlh+9EUR3gUSul9YVmCdZxWpKgPba3Vm9faaIkoG63uvogLr3ksUN2g3CqWo6AFnOEWNUeRQmfo4BGKhcIzKqR3CBE5QQxzrEb6XbhrwM5xCKQX9hvWZfUPrncwksWM4UuynkicMJLs86EwnJeMdjc8VTy411+eGRJZCCE4RfLx+yzA2da3xBudw9ior9MonePhHXA/8FZZgdV+5fSKpJnI/BFRlb+2+ERv5vxd0KkQUhNqo4VXT4WYT2gL2H23u0dPr/dBJfECH/KoVfN5CasVYf0J0AqL0M1j2USZUlg50YAQoPkLPaUyI+b/fg+P3FV5goXYpTBZn0b32JtItkRBwjZMR2QnUVvQUgXbLzti/QpqblIKN47HGPIEchXiUxx//l1rvs=
  bucket: static-source-ndavies-io
  acl: ''
  on:
    repo: daviesnathan/ndavies.io
